Neos:
  Imagine:
    driver: Gmagick
  Flow:
    persistence:
      backendOptions:
        driver: pdo_mysql
        dbname: neos
        user: neos
        password: neos
        host: 0.0.0.0
        port: 13306
